# NUMPY
- ndarray

In [3]:
# range
list(range(5))

[0, 1, 2, 3, 4]

In [5]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
list(range(0,10,5))

[0, 5]

In [11]:
list(range(0,5,1,1)) # rangfe takes max 3 arguments and end index will not print 

TypeError: range expected at most 3 arguments, got 4

In [15]:
list(range(20,5)) # nothing printed as left index is >  right index

[]

- 1d array
- 2d array
- nd array
- ver powerful library 

In [18]:
import numpy as np

In [20]:
np.__version__

'1.26.4'

In [22]:
import sys
sys.version

'3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)]'

## creating Aray

In [27]:
my_list = [0,1,2,3,4,5]

In [29]:
type(my_list)

list

In [31]:
# convert list to array
arr =  np.array(my_list)

In [33]:
arr

array([0, 1, 2, 3, 4, 5])

In [39]:
np.arange(15) # start=0 stop=(n-1) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [41]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [43]:
np.arange(7.9)

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [45]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.arange(5,50,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [51]:
np.arange(20,10) # 1at arg < 2nd arg

array([], dtype=int32)

In [55]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [57]:
np.arange(-20,-5)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6])

In [59]:
arr1  = np.arange(-30,20)

In [61]:
arr1

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [65]:
np.arange(10,10)

array([], dtype=int32)

In [67]:
np.arange(0,10,2,4)

TypeError: Cannot interpret '4' as a data type

In [71]:
np.zeros(3)   # parameter tuning

array([0., 0., 0.])

In [73]:
np.zeros(5, dtype = int)   # hyper parameter tuning

array([0, 0, 0, 0, 0])

In [75]:
np.zeros((3,4), dtype= int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [79]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [81]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [83]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [85]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [89]:
np.zeros((2,10,1))

array([[[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]]])

In [91]:
np.ones(3)

array([1., 1., 1.])

In [93]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [95]:
np.ones((3,5,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [97]:
np.ones((3,5,2), dtype = int)

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [105]:
np.twos((5,6))

AttributeError: module 'numpy' has no attribute 'twos'

In [103]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [113]:
import random

In [125]:
np.random.rand(8)

array([0.62712352, 0.32308848, 0.65932003, 0.97573203, 0.79316056,
       0.65888465, 0.55870762, 0.22075859])

In [131]:
np.random.rand(1,4 )

array([[0.42085653, 0.38196624, 0.00164453, 0.72833107]])

In [133]:
np.random.rand(10,5,5,6)

array([[[[0.73582275, 0.08986269, 0.65208875, 0.20158434, 0.74068792,
          0.41773636],
         [0.13324248, 0.67573958, 0.60496922, 0.79738139, 0.67175939,
          0.88999005],
         [0.37779235, 0.26969161, 0.63678658, 0.86818567, 0.64737402,
          0.05942693],
         [0.02870883, 0.74724018, 0.19136799, 0.38644333, 0.83058719,
          0.73020495],
         [0.69735842, 0.73078831, 0.38650127, 0.54666755, 0.18235877,
          0.76524459]],

        [[0.17364669, 0.80131861, 0.63240742, 0.31299143, 0.63966872,
          0.74304567],
         [0.57154578, 0.53544573, 0.97435215, 0.35072468, 0.38792207,
          0.66216287],
         [0.14267285, 0.34396304, 0.30652654, 0.06675605, 0.5204167 ,
          0.58621795],
         [0.19132356, 0.5631397 , 0.64687912, 0.31569858, 0.33172959,
          0.40184307],
         [0.4947663 , 0.25543822, 0.27490473, 0.27963827, 0.74623801,
          0.68447135]],

        [[0.56519835, 0.33609515, 0.58933231, 0.07952522, 0.593241

In [135]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [137]:
np.random.randint(4,5)

4

In [139]:
np.random.randint(1234)

504

In [141]:
random.randint(5,500)

301

In [143]:
np.random.randint(5,500,(4,5))

array([[264, 463, 498, 263,  49],
       [420, 465, 447,  11, 299],
       [ 56,  96, 182,  97, 266],
       [350, 464, 277, 357,  22]])

In [145]:
np.random.randint(0,100,(5,6))

array([[93,  1, 57, 56, 29, 18],
       [77, 66, 43, 28, 12, 85],
       [73, 77,  8, 79, 62,  9],
       [ 6, 56, 59,  6, 53, 55],
       [99, 11, 14, 15, 10, 71]])

In [147]:
arr3  = np.random.randint(0,100,(5,6))

In [149]:
arr3[0:]

array([[37, 79, 42, 17,  3, 92],
       [90, 17, 96, 68, 44, 87],
       [66, 36, 87, 56, 90, 59],
       [39, 80, 29, 38, 67, 43],
       [ 9, 63, 83, 99,  8, 34]])

In [151]:
np.random.rand(5)

array([0.4205197 , 0.18673746, 0.38904106, 0.20002743, 0.28517281])

In [153]:
np.random.rand(5,6)

array([[0.29048277, 0.47020707, 0.64752124, 0.08228112, 0.40036217,
        0.12516076],
       [0.82190815, 0.94280403, 0.28320558, 0.60391327, 0.73698796,
        0.18515556],
       [0.09306715, 0.27922421, 0.09457852, 0.61341422, 0.32802039,
        0.16920539],
       [0.87913487, 0.3252909 , 0.39122696, 0.22542204, 0.59675761,
        0.00472833],
       [0.2567454 , 0.14983193, 0.80088353, 0.96052874, 0.16551536,
        0.28146816]])

In [155]:
np.random.rand(5,7,1)

array([[[0.438424  ],
        [0.47350117],
        [0.08171459],
        [0.79549085],
        [0.4758589 ],
        [0.9865724 ],
        [0.29007645]],

       [[0.29448807],
        [0.74610698],
        [0.58693033],
        [0.48419451],
        [0.37659979],
        [0.71045576],
        [0.27527116]],

       [[0.69906178],
        [0.48865857],
        [0.11338364],
        [0.28183928],
        [0.87723418],
        [0.19054132],
        [0.23284353]],

       [[0.41880366],
        [0.10218851],
        [0.82704448],
        [0.54168308],
        [0.99649759],
        [0.89177127],
        [0.4626462 ]],

       [[0.14051528],
        [0.73285401],
        [0.09260551],
        [0.89192113],
        [0.84650477],
        [0.53644917],
        [0.57531519]]])

In [157]:
arr3 = np.random.rand(5,7,1)

In [163]:
arr3*4

array([[[0.39788293],
        [0.71233643],
        [3.80154467],
        [3.40076947],
        [3.52041441],
        [1.09201991],
        [0.36005349]],

       [[3.94325428],
        [2.62701599],
        [3.21659661],
        [0.82868907],
        [3.09151115],
        [2.60174672],
        [1.02827253]],

       [[2.56750988],
        [2.76044445],
        [2.00453666],
        [1.40230155],
        [0.41513754],
        [1.09681709],
        [2.19704692]],

       [[3.75663041],
        [2.5360809 ],
        [0.78388447],
        [3.67348683],
        [3.84151684],
        [2.24516241],
        [1.16975535]],

       [[0.32822081],
        [0.66196402],
        [3.48401066],
        [1.12902175],
        [0.79553383],
        [1.9343981 ],
        [2.99414799]]])

In [167]:
np.random.randint(5)

4

In [169]:
np.random.randint(1,50)

13

In [173]:
np.random.randint(1,50,(5,6))

array([[20, 14, 35, 41, 21,  5],
       [23, 40, 12, 19, 30,  6],
       [40,  4, 26,  9, 40,  4],
       [13, 44, 23,  2, 16, 48],
       [42, 48, 23,  7, 11,  2]])

In [177]:
np.random.rand(1,5)

array([[0.1247723 , 0.36336138, 0.3138653 , 0.2692224 , 0.36844337]])

In [179]:
data = np.array([[1, 2], [5, 3], [4, 6]])

In [181]:
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [185]:
data.shape

(3, 2)

In [189]:
data.ndim

2

In [193]:
data.size

6

In [195]:
data.sum()

21

In [197]:
data.sum(axis=0)

array([10, 11])

In [203]:
arr3

array([[[0.09947073],
        [0.17808411],
        [0.95038617],
        [0.85019237],
        [0.8801036 ],
        [0.27300498],
        [0.09001337]],

       [[0.98581357],
        [0.656754  ],
        [0.80414915],
        [0.20717227],
        [0.77287779],
        [0.65043668],
        [0.25706813]],

       [[0.64187747],
        [0.69011111],
        [0.50113416],
        [0.35057539],
        [0.10378439],
        [0.27420427],
        [0.54926173]],

       [[0.9391576 ],
        [0.63402022],
        [0.19597112],
        [0.91837171],
        [0.96037921],
        [0.5612906 ],
        [0.29243884]],

       [[0.0820552 ],
        [0.165491  ],
        [0.87100266],
        [0.28225544],
        [0.19888346],
        [0.48359952],
        [0.748537  ]]])

In [207]:
arr3.ndim

3

In [209]:
arr3.shape

(5, 7, 1)

In [211]:
arr3.max(axis=0)

array([[0.98581357],
       [0.69011111],
       [0.95038617],
       [0.91837171],
       [0.96037921],
       [0.65043668],
       [0.748537  ]])

In [213]:
arr3.max(axis=1)

array([[0.95038617],
       [0.98581357],
       [0.69011111],
       [0.96037921],
       [0.87100266]])

In [215]:
arr3

array([[[0.09947073],
        [0.17808411],
        [0.95038617],
        [0.85019237],
        [0.8801036 ],
        [0.27300498],
        [0.09001337]],

       [[0.98581357],
        [0.656754  ],
        [0.80414915],
        [0.20717227],
        [0.77287779],
        [0.65043668],
        [0.25706813]],

       [[0.64187747],
        [0.69011111],
        [0.50113416],
        [0.35057539],
        [0.10378439],
        [0.27420427],
        [0.54926173]],

       [[0.9391576 ],
        [0.63402022],
        [0.19597112],
        [0.91837171],
        [0.96037921],
        [0.5612906 ],
        [0.29243884]],

       [[0.0820552 ],
        [0.165491  ],
        [0.87100266],
        [0.28225544],
        [0.19888346],
        [0.48359952],
        [0.748537  ]]])

In [221]:
arr3.shape
arr4 = arr3.reshape(arr3.shape)

In [223]:
arr3*arr4

array([[[0.00989443],
        [0.03171395],
        [0.90323387],
        [0.72282706],
        [0.77458235],
        [0.07453172],
        [0.00810241]],

       [[0.97182839],
        [0.43132581],
        [0.64665586],
        [0.04292035],
        [0.59734008],
        [0.42306787],
        [0.06608402]],

       [[0.41200669],
        [0.47625335],
        [0.25113545],
        [0.1229031 ],
        [0.0107712 ],
        [0.07518798],
        [0.30168845]],

       [[0.882017  ],
        [0.40198165],
        [0.03840468],
        [0.84340659],
        [0.92232823],
        [0.31504714],
        [0.08552047]],

       [[0.00673306],
        [0.02738727],
        [0.75864564],
        [0.07966813],
        [0.03955463],
        [0.2338685 ],
        [0.56030764]]])

In [227]:
arr3*5

array([[[0.49735366],
        [0.89042054],
        [4.75193083],
        [4.25096183],
        [4.40051801],
        [1.36502489],
        [0.45006686]],

       [[4.92906785],
        [3.28376999],
        [4.02074576],
        [1.03586134],
        [3.86438894],
        [3.2521834 ],
        [1.28534066]],

       [[3.20938735],
        [3.45055557],
        [2.50567082],
        [1.75287694],
        [0.51892193],
        [1.37102137],
        [2.74630865]],

       [[4.69578801],
        [3.17010112],
        [0.97985558],
        [4.59185853],
        [4.80189605],
        [2.80645302],
        [1.46219419]],

       [[0.41027601],
        [0.82745502],
        [4.35501332],
        [1.41127718],
        [0.99441729],
        [2.41799762],
        [3.74268499]]])